name: Reference book for Verovio
baseurl: ""
exclude: ['scripts']

verovio-version: 3.4

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    #css_class   : 'syntax'

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

sass:
  sourcemap: never

theme: verovio-theme

plugins:
  - "jekyll-github-metadata"

edit-path: "https://github.com/rism-digital/verovio-reference-book/edit/master"

defaults:
  - scope:
      path: ""
    values:
      layout: book
      verovio: false
      active: book

collections:
    book:
        output: true

generate-full-chapters: true