name: Verovio music engraving library
baseurl: ""
exclude: []

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    #css_class   : 'syntax'

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

sass:
  sourcemap: never

theme: verovio-theme

tests-edit-path: "https://github.com/rism-digital/verovio.org/edit/gh-pages"
tests-verovio-edit-path: "https://editor.verovio.org/?file=https://raw.githubusercontent.com/rism-digital/verovio.org/gh-pages"

defaults:
  - scope:
      path: ""
    values:
      layout: book
      verovio: false
      active: book

collections:
    book:
        output: true